### ISSUE TITLE
Facebook Messenger / Tool Bar

### ISSUE THREAD

**Issue by vouxiong** [devotoare/android-messages-launcher#1]
The Chrome Extension for **Messages for Web** cannot switch between **SMS** messages and Facebook Messages. There use to be a toolbar now I can no logger see it.

**Comment by devotoare** [comment]
That's odd that there was a toolbar. This specifically opens a window with no toolbars to https://messages.android.com/ and doesn't do anything else. There should not have been a button for Facebook Messenger before, sorry.
